# Generated by Django 4.1.7 on 2023-03-01 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(db_index=True, max_length=30, unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.TextField(max_length=30, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.TextField(max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_number', models.TextField(max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steerable_axle_number', models.TextField(max_length=50, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.TextField(blank=True, max_length=50, verbose_name='Договор поставки №, дата.')),
                ('shipping_date', models.DateField(db_index=True, verbose_name='Дата отгрузки с завода')),
                ('consignee', models.TextField(blank=True, max_length=50, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.TextField(blank=True, max_length=150, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(blank=True, max_length=150, verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Машины',
                'ordering': ['shipping_date'],
            },
        ),
        migrations.CreateModel(
            name='Drive_axle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='Engine_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='Failure_node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
            },
        ),
        migrations.CreateModel(
            name='Organization_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация, проводившая ТО',
            },
        ),
        migrations.CreateModel(
            name='Recovery_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='Steerable_axle_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='Technique_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='Transmission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Type_maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='Service_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(verbose_name='Наработка м/час')),
                ('work_order', models.TextField(max_length=50, verbose_name='№ заказа-наряда')),
                ('date_work_order', models.DateField(verbose_name='Дата заказа-наряда')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.car', verbose_name='Машина')),
                ('organization_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.organization_maintenance', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.type_maintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'ordering': ['maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.IntegerField(verbose_name='Наработка м/час')),
                ('description_failure', models.TextField(max_length=1024, verbose_name='Характер отказа')),
                ('parts_used', models.TextField(verbose_name='Используемые запасные части')),
                ('date_of_restoration', models.DateField(verbose_name='Дата восстановления')),
                ('equipment_downtime', models.IntegerField(verbose_name='Время простоя техники')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.car', verbose_name='Машина')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.failure_node', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.recovery_method', verbose_name='Способ восстановления')),
                ('service_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация')),
            ],
            options={
                'verbose_name': 'Рекламации',
                'ordering': ['date_of_refusal'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.drive_axle_model', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.engine_model', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.service_company', verbose_name='Сервисная организация'),
        ),
        migrations.AddField(
            model_name='car',
            name='steerable_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.steerable_axle_model', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='technique_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.technique_model', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant.transmission_model', verbose_name='Модель трансмиссии'),
        ),
    ]
