# Generated by Django 4.0.5 on 2023-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='equipment_downtime',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Время простоя техники'),
        ),
    ]
