# Generated by Django 4.0.5 on 2023-03-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['maintenance_date'], 'permissions': (('view_maintenance_noclient', 'Can view no client'),), 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
    ]
