# Generated by Django 4.0.5 on 2023-03-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_complaints_equipment_downtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['shipping_date'], 'permissions': (('view_car_noclient', 'Can view no client'),), 'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
    ]
