# Generated by Django 4.0.5 on 2023-03-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_failure_node_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['shipping_date'], 'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['date_of_refusal'], 'verbose_name': 'Рекламации', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='drive_axle_model',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='engine_model',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателя'},
        ),
        migrations.AlterModelOptions(
            name='failure_node',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['maintenance_date'], 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterModelOptions(
            name='organization_maintenance',
            options={'verbose_name': 'Организация, проводившая ТО', 'verbose_name_plural': 'Организации, проводившая ТО'},
        ),
        migrations.AlterModelOptions(
            name='recovery_method',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='service_company',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='steerable_axle_model',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='technique_model',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
        migrations.AlterModelOptions(
            name='transmission_model',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AlterModelOptions(
            name='type_maintenance',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
    ]
