# Generated by Django 4.0.5 on 2023-03-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0003_alter_complaints_options_alter_maintenance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['shipping_date'], 'permissions': (('view_car_noclient', 'Can view no client'), ('view_car_noservice', 'Can view no service')), 'verbose_name': 'Машины', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['date_of_refusal'], 'permissions': (('view_complaints_noclient', 'complaints view no client'), ('view_complaints_noservice', 'Can view no service')), 'verbose_name': 'Рекламации', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['maintenance_date'], 'permissions': (('view_maintenance_noclient', 'maintenance view no client'), ('view_maintenance_noservice', 'Can view no service')), 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
    ]
